spring.application.name=kotihoito

# H2 konfiguraatio
# spring.datasource.url=jdbc:h2:mem:kotihoito
# spring.datasource.driver-class-name=org.h2.Driver

# Postgre konfiguraatio
spring.datasource.url=jdbc:postgresql://localhost:5432/kotidb
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate configuration
# Kirjoita perään create-drop (jos on H2) tai sitten validate (jos on PostgreSQL)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Kirjoita perään joko H2Dialect tai PostgreSQLDialect riippuen siitä, kumpaa tietokantaa käytät
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect